# Generated by Django 4.2 on 2025-02-19 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_alter_book_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="book",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="book",
            name="publication_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="book",
            name="stock",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="book",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
