# Generated by Django 4.2 on 2025-02-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_alter_book_author_alter_book_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"managed": True},
        ),
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(max_length=13),
        ),
    ]
