# Generated by Django 4.2 on 2025-02-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_alter_book_options_alter_book_image_alter_book_isbn"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={},
        ),
        migrations.AlterField(
            model_name="book",
            name="_id",
            field=models.CharField(max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="book",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="books/"),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="book",
            name="publication_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
